services:
  fs-indicators:

    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fs-indicators.tls=true"
      - "traefik.http.routers.fs-indicators.tls.certresolver=letsencrypt"
      - "traefik.http.routers.fs-indicators.entrypoints=websecure"
      - "traefik.http.routers.service=fs-indicators-service"
      - "traefik.http.services.fs-indicators-service.loadbalancer.server.port=8050"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.fs-indicators.rule=Host(`fs-indicators.fsobs.org`)"

networks:
  traefik:
    external: true
